- copy:
    dest: /etc/yum.repos.d/influxdb.repo
    src: etc/yum.repos.d/influxdb.repo

- yum:
    name: influxdb

- template:
    dest: /etc/influxdb/influxdb.conf
    src: etc/influxdb/influxdb.conf.j2
  notify:
    - restart influxdb service

- service:
    name: influxdb
    state: started
  run_once: true

- template:
    dest: /etc/default/influxdb
    src: etc/default/influxdb.j2

- service:
    name: influxdb
    state: started
    enabled: true

- shell: influx -host {{ ansible_default_ipv4.address }} -execute "SHOW DATABASES" | grep -q 'mytest'
  register: check_mytest_database
  failed_when: false
  changed_when: false
  always_run: true
  ignore_errors: true
  run_once: true

- shell: influx -host {{ ansible_default_ipv4.address }} -execute "CREATE DATABASE mytest"
  when: check_mytest_database.rc != 0
  run_once: true

- shell: influx -host {{ ansible_default_ipv4.address }} -execute "SHOW USERS" | grep -q 'mytest'
  register: check_mytest_user
  failed_when: false
  changed_when: false
  always_run: true
  ignore_errors: true
  run_once: true

- shell: influx -host {{ ansible_default_ipv4.address }} -execute "CREATE USER mytest WITH PASSWORD 'mytest'"
  when: check_mytest_user.rc != 0
  run_once: true

- shell: influx -host {{ ansible_default_ipv4.address }} -execute "GRANT ALL ON mytest TO mytest"
  when: check_mytest_user.rc != 0
  run_once: true
