- service:
    name: influxdb
    state: stopped
    enabled: false

- file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/influxdb
    - /etc/default/influxdb
    - /etc/influxdb
